---
title: Teken een rechthoek
hero_image: images/banner.png
description: Teken een rechthoek met behulp van Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - 
    title: Inleiding
