title: Draw a rectangle
hero_image: images/banner.png
description: Draw a rectangle using processing in Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - title: Introduction
