---
title: Dessiner un rectangle
hero_image: images/banner.png
description: Dessiner un rectangle en utilisant Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - 
    title: Introduction
